FROM python:3.10

WORKDIR /app
COPY . /app

RUN pip install -r /app/requirements.txt

ENV PYTHONUNBUFFERED 1

ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
